project_root: "/work/bk1318/k202208/crai/hindcast-pp/Ml-Drought-Postprocessing"
external_data_root: "/work/bk1318/k202208/crai/hindcast-pp/data"

experiment: "cwb"
leadtime_tag: "lm1-6"

hindcasts_json: "${project_root}/droughtpp/data/train/${experiment}/dwd-hindcasts_${leadtime_tag}_test.json"
residuals_json: "${output_dir}/data/paths/qm_residuals_paths.json"

reference_data: "${external_data_root}/spei/${experiment}/era5/era5-tamsat_cwb_remapped_invlat.nc"
reference: "${reference_data}"

output_dir: "${project_root}/droughtpp/eval_results/${experiment}/qm_rf"
model_dir: "${output_dir}/model"
model_name: "rf-basic"
corrected_spei_paths_json: "${output_dir}/data/paths/corrected_spei_paths.json"
corrected_residuals_json: "${output_dir}/data/paths/corrected_residuals_paths.json"
corrected_cwb_json: "${output_dir}/data/paths/corrected_cwb_paths.json"
hindcasts_spei_json: "${output_dir}/data/spei/original_hindcasts_spei_paths.json"
qm_hindcasts_spei_json: "${output_dir}/data/spei/qm_hindcasts_spei_paths.json"
reference_spei_json: "${output_dir}/data/spei/reference_spei_paths.json"

var_name: "CWB"
predictor_vars: ["CWB"]
additional_reference_features:
  - name: tas
    path: /work/bk1318/k202208/crai/hindcast-pp/data/spei/era5/tas/era5-monthly/tas_Amon_reanalysis_era5_r1i1p1_19400101-20241231_tamsatregion_dwdgrid.nc
    var_name: tas
  - name: precip
    path: /work/bk1318/k202208/crai/hindcast-pp/data/spei/era5/precip/tamsat/tamsat_precip_monthly_1983-2024_dwdgrid.nc
    var_name: rainfall_estimate_filled
  - name: cwb_clim
    path: /work/bk1318/k202208/crai/hindcast-pp/data/spei/cwb/era5/era5-tamsat_cwb_remapped_invlat_climatology.nc
    var_name: CWB
    mode: monthly_climatology
leave_out_years: [2010, 2011, 2012, 2013, 2014]

spei_month_range: [1, 3]
spei_std_multiplier: 1.0

workflow:
  run_qm: true 
  run_qm_eval: false 
  run_rf_train: true 
  run_rf_evaluate: true 
  evaluate_cwb: true
  evaluate_spei: false 

data_dir: "${external_data_root}/spei/"
input_dir: "${project_root}/droughtpp/data/"
spei_json: null

n_estimators: 20
random_state: 0
chunk_size: 10
leadmonth: [1, 2, 3, 4, 5, 6]

plot_dir: "${output_dir}/plots/"
qm_json_path: "${output_dir}/data/paths/qm_hindcast_paths.json"
n_quantiles: 20
bins: 50
show: false